### ISSUE TITLE
connection drop intermittently 

### ISSUE THREAD

**Issue by gflarity** [lwfinger/rtl8723au#17]
Not sure if I should have opened a new issue, this is with WPA personal not enterprise.  I can't get a large download (100megs) to succeed before it times out. It wouldn't connect to anything for a while and then it comes back. Is there anything I can do? 

Here's the dmesg output, there's probably a lot of noise in here, sorry, not sure what you'd want to see.  Thanks in advance for looking at this/all the work thats gone into this. It's appreciated.

[    3.755752] RTL8723AU: ERROR indicate disassoc
[    3.771124] RTL8723AU: ERROR indicate disassoc
[    3.779121] RTL8723AU: ERROR indicate disassoc
[    3.779976] RTL8723AU: ERROR set bssid:00:00:00:00:00:00
[    3.780017] RTL8723AU: ERROR set ssid [g\xffffffc6isQ\xffffffffJ\xffffffec)\xffffffcd\xffffffba\xffffffba\xffffffab\xfffffff2\xfffffffb\xffffffe3F|\xffffffc2T\xfffffff8\x1b\xffffffe8\xffffffe7\xffffff8dvZ.c3\xffffff9f\xffffffc9\xffffff9a\xffffff9aD\xffffffcc1;] fw_state=0x00000008
[    6.507290] RTL8723AU: ERROR set ssid [MsV] fw_state=0x00000008
[    6.507304] RTL8723AU: ERROR set bssid:00:26:5a:f1:41:26
[    6.590978] RTL8723AU: ERROR start auth
[    6.593768] RTL8723AU: ERROR auth success, start assoc
[    6.597815] RTL8723AU: ERROR assoc success
[    9.607370] RTL8723AU: ERROR send eapol packet
[    9.613179] RTL8723AU: ERROR send eapol packet
[    9.613225] RTL8723AU: ERROR set pairwise key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4) camid:4
[    9.615000] RTL8723AU: ERROR set group key to hw: alg:2(WEP40-1 WEP104-5 TKIP-2 AES-4) keyid:2
[  139.932853] RTL8723AU: ERROR indicate disassoc
[  139.932911] RTL8723AU: ERROR set bssid:00:00:00:00:00:00
\xffffffb71X\xffffffa3Z%]\x05\x17X\xffffffe9^\xffffffd4\xffffffab\xffffffab\xffffffb2\xffffffcd\xffffffc6\xffffff9b\xffffff9b\xffffffb4T\x11\x0e\xffffff82tA!=\xffffffdc\xffffff87\xffffff87D\xffffffcc1;] fw_state=0x00000008
[  139.937187] RTL8723AU: ERROR sta recv deauth reason code(6) sta:00:26:5a:f1:41:26
[  139.938306] RTL8723AU: ERROR sta recv deauth reason code(6) sta:00:26:5a:f1:41:26
[  139.967779] RTL8723AU: ERROR indicate disassoc
[  146.097495] RTL8723AU: ERROR nolinked power save enter
[  166.491892] RTL8723AU: ERROR nolinked power save leave
[  168.493752] RTL8723AU: ERROR nolinked power save enter
[  199.494796] RTL8723AU: ERROR nolinked power save leave
[  201.495866] RTL8723AU: ERROR nolinked power save enter
[  242.502575] RTL8723AU: ERROR nolinked power save leave
[  244.503800] RTL8723AU: ERROR nolinked power save enter
[  295.511974] RTL8723AU: ERROR nolinked power save leave
[  297.513616] RTL8723AU: ERROR nolinked power save enter

**Comment by romines** [comment]
@joedborg I'm sure you figured this out, but JIC:

Create a .conf file such as 8723au.conf that contains the following:
`options rtl8723au fwlps=0 swlps=0 rtw_power_mgnt=0`
