### ISSUE TITLE
Lenovo Yoga 11s wifi unusable

### ISSUE THREAD

**Issue by davidmattson1** [lwfinger/rtl8723au#59]
My wifi would connect but when I tried to download anything or go to any webpage it would start the download but quickly disconnect from wifi.  I blacklisted the r8723au driver but then I also blacklisted the 8723au driver and it works without disconnecting now.  

I read in one of your other posts that you don't actually have the RTL8723au chip in anything.  What logs etc would you need to troubleshoot this?

I'm running Arch with the 4.7.0.1 kernel

Much appreciated, thank you

**Comment by lwfinger** [comment]
Why not use driver rtl8xxxu from kernel 4.7? It is being maintained by the author. If it gives you trouble, report it at linux-wireless@vger.kernel.org.

**Comment by davidmattson1** [comment]
It used r8723au first until I blacklisted it.  Guess I wasn't sure that rtl8xxxu was right.  Thanks!  I'll use that.
